version: '3.9'
services:
  app:
    container_name: backend-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_BUILDKIT: 1

    deploy:
      resources:
        limits:
          memory: 4096M
        reservations:
          memory: 2048M
    restart: unless-stopped
    ports:
      - '${APPLICATION_PORT}:3000'
    volumes:
      - .:/usr/src/app
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: database
    image: mysql:8.0.37
    restart: unless-stopped
    command: [ '--default-authentication-plugin=caching_sha2_password', '--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION' ]
    ports:
      - '${DATABASE_EXTERNAL_PORT}:3306'
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_TEST_DATABASE: '${DATABASE_TEST_NAME}'
      MYSQL_DEFAULT_DATABASE: '${DATABASE_NAME}'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      start_period: 30s
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  db_data:
